<?php
/**
 * @file
 * Code for the Survey Questions feature.
 */

include_once 'survey_questions.features.inc';

/**
 * hook only called for add/edit coalition_profile node
 */
function survey_questions_node_prepare($node) {
  $type = node_type_get_type($node);

  if ($type->type == 'coalition_profile')
    drupal_add_js('jQuery(document).ready(function () { gsl_survey_questions_on_form_load(); });', 'inline');
}
